
[general]

	[general.category]
		color_picker = "255,0,0,255"
		color_pickerdas = "255,255,0,0"
		color_pickeraaaaaa = "255,0,0,255"
		text = ""
		enable_harp_solver = false

[developer_tools]
	enable_auto_updater = false

[attribute_viewer]
	enable_for_other_items = true
	enable_attribute_viewer = true
	enable_for_attribute_shards = true
	enable_only_in_auction_house = false

[auto_fishing]
	enable_auto_fishing = true

[harp_solver]
	enable_harp_solver = true

	[harp_solver.category]
		enable_harp_solver = false

